from ftg.__help.utils import to_link, Section

header = "Why Filenames?"
link = to_link(header)

text = str(
    F'# {header}\n'
    '\n'
    'This is the conclusion of a [reddit post](https://www.reddit.com/r/battlemaps/comments/vuk9uw/working_on_a_tagging_tool_for_map_hoarders_need/)\n'
    '\n'
    '# Summary\n'
    '\n'
    '- Filenames are a good enough solution in the majority of cases.\n'
    '- Every good enough solution is better than a perfect solution that is never finished. (It has already taken me too long to implement this)\n'
    '- Every alternative to filenames I found so far either had other limitations or would require 100s of hours of work\n'
    '  to produce a satisfying program.\n'
    '- I don\'t get paid so can\'t spend 100s of hours implementing niche tools that only a handful of people will use.\n'
    '\n'
    '## Why Filenames are Good\n'
    '\n'
    '- Very verbose, can see tags with every file browser\n'
    '- Re-using what already exists\n'
    '    - File browser\n'
    '    - Thumbnail cache\n'
    '    - Search and indexing functionality\n'
    '    - Image viewers\n'
    '- Works in pretty much every cloud web interface\n'
    '    - => Access your media files via tags everywhere without having to download them first\n'
    '- Works with every type of file\n'
    '- Tags don\'t get lost on conversion\n'
    '- Tags don\'t get lost when file is moved\n'
    '- Tags always stay synced with file even when working on multiple machines \n'
    '  - => No need to sync databases, metafiles etc.\n'
    '\n'
    '## Problems with Alternative Solutions\n'
    '\n'
    '### Database\n'
    '\n'
    '- What happens when files are moved outside the tool?\n'
    '- Would require indexing\n'
    '- Needs a thumbnail cache and a file browser with search functionality\n'
    '- How to sync the database to different PCs?\n'
    '- Can\'t use tags in the cloud web interface\n'
    '- Would basically just re-implement one of the countless tagging solutions that already exist\n'
    '\n'
    '### Accompanying Metafiles\n'
    '\n'
    '- Files always have to be moved together\n'
    '- Would require indexing\n'
    '- Needs a thumbnail cache and a file browser with search functionality\n'
    '- Can\'t use tags in the cloud web interface\n'
    '\n'
    '### Metadata of the Files\n'
    '\n'
    '- Not supported for a lot of file types\n'
    '- Would need to treat every file type special\n'
    '- Would require indexing\n'
    '- Needs a thumbnail cache and a file browser with search functionality\n'
    '- Can\'t use tags in the cloud web interface'
)

section = Section(link,
                  header,
                  text)
